import 'package:flutter/widgets.dart';

const ICON_COLOR = Color(0xFFD2DCE8);
const BACKGROUND_COLOR = Color(0xFF262B40);
const MENU_BUTTON_COLOR = Color(0xFF3C3F53);
const TITLE_TEXT_COLOR = Color(0xFF1C1E31);
const SUB_TITLE_TEXT_COLOR = Color(0xFF9394A0);
const TASK_APPROVED_COLOR = Color(0xFF34B0AD);
const TASK_APPROVED_BG_COLOR = Color(0xFFDAF3F1);
const TASK_PROGRESS_COLOR = Color(0xFF4887ED);
const TASK_PROGRESS_BG_COLOR = Color(0xFFDCEAFC);
const TASK_REVIEW_COLOR = Color(0xFFEC896D);
const TASK_REVIEW_BG_COLOR = Color(0xFFFDEAE2);
const TASK_WAITING_COLOR = Color(0xFF75808E);
const TASK_WAITING_BG_COLOR = Color(0xFFE7EAEC);
